apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/chtourou-youssef/game-of-pods.git
    targetRevision: HEAD
    path: path: ./app-of-apps/manifests/front
    
   
  destination:
    server: https://kubernetes.default.svc
    namespace: multiple

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
