apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      db: dev
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-deployment
        image: postgres:9.4
        env:
         - name: POSTGRES_PASSWORD
           value: testpassword
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        emptyDir: {}
