kind: Service
apiVersion: v1
metadata:
  name: result-service
  namespace: vote
spec:
  type: NodePort
  selector:
    app: result
  ports:
    - port: 5001
      targetPort: 80
      nodePort: 31001
      protocol: TCP
