apiVersion: v1
kind: Service
metadata:
  name: b2b-laravel
spec:
  selector:
    app: b2b-laravel
  # Change to NodePort to expose
  type: ClusterIP
  ports:
    - name: server
      port: 80
      # nodePort: 32101
    - name: web-socket
      port: 6002
