apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  namespace: default
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/vol"      
