apiVersion: v1
kind: Service
metadata:
  name: stark-front-svc
  labels:
    app: front
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: front
  type: LoadBalancer
