apiVersion: apps/v1
kind: Deployment
metadata:
  name: stark-front-dep
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: stark-front 
        image: tomcat 
        ports:
        - name: tomcat
          containerPort: 8080

