apiVersion: v1
kind: Service
metadata:
  name: stark-front-svc
  labels:
    app: front
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30098
  selector:
    app: front
  type: NodePort
