apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app
  name: dep-svc
spec:
  ports:
  - 
    port: 5678
    protocol: TCP
    targetPort: 80
  selector:
    app: web-app
  type: NodePort
