---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secrets
  namespace: default
spec:
  encryptedData:
    ROOT_PASSWORD: AgBwqiFCRmcTwlfjRvIno9VCnncIRYjInQpBZe0vloMnv5DoM64RxYadIREFgu3bw8Vb3D2hvzW849rzS3726kUx1+z8qWvIph/4bq5NYYSS8xrSG/tyKoJPTSWboUY5RmLJEhcLQo4Aisvr2K44m0QTQBXZ2UD1Vfy4mOEQPtRDZZeSZ1f7n9jtcNr2y15TQ5vhcONBy40tVNPru21rHKKn0yySJqZXVW2ye4aTF6v5QSzvN1RwQBUGlHb5I8GkxONCE5gZeaDMvKK+GDhSPU7FRS5fkl+2EogdgyClQ5hkqLiLQauu91jdJ2jHaOwGm8CKgJ41AIZLzEQsOxE9mf4utwJ7bkpUxQ7fraVl+PgBzRjh1rn9LxhAsEpBLcBLiLU99zoFZEEeS9TJbogQWi7lpu+cW+Znog99oviOY689gZEslZw33WAP4HeDnXEo7BmDuCCz/bH0nKXNou4SlC0cnDq1GVZEePcty/MUl5I1lGX6BcR+BUHrG06g29YxpecgqCw81el3oa8spd+bzBvU0C5/HYu3JK707XqG9RXJ7PsjmVBJ5WN/EzBiP1i5GPDU0466VobP7asl9wa+58c3T/ZvKcT5u+8l/i5bZlcgisWqWwYn6wPJ0DXs2tZX15WRG7EP0/mws+QXCPre7UUoHIjGjsASXa0i4qi5qKHBmPub34h6+kNBV8P0QnI6DzAHfuQolSmBdDTwZ836oCw=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secrets
      namespace: default
    type: Opaque
